### PR TITLE
chore: upgrade wd to v1.10.1

### PR DESCRIPTION
**Pull request by aaarichter**
upgrading to the latest available version https://github.com/admc/wd

### CODE REVIEW

**Comment by jkrems** [comment]
Looks like you based this on an outdated master branch. Can you try `git fetch origin master && git rebase origin/master`?

**Comment by aaarichter** [comment]
just rebased @jkrems

**Comment by dbushong** [comment]
This doesn't really change anything, because `^` includes minor version bumps

**Comment by aaarichter** [comment]
oddly on fresh node_modules install via yarn the yarn.lock still shows
```

wd@^1.0.0:
  version "1.6.2"
  resolved "https://npm.groupondev.com:443/api/npm/npm-release/wd/-/wd-1.6.2.tgz#92576ee11a5c792aa0249ea097e020ece1ed740e"
  dependencies:
    archiver "1.3.0"
    async "2.0.1"
    lodash "4.16.2"
    mkdirp "^0.5.1"
    q "1.4.1"
    request "2.85.0"
    underscore.string "3.3.4"
    vargs "0.1.0"
```

**Comment by aaarichter** [comment]
after deleting yarn.lock as well I got wd v1.10.1

**Comment by jkrems** [comment]
(Btw, no label on this PR because it originated from a fork. This is a limitation for how we're setting up `nlm` on public repos... :()

**Pull request merged**
