### PR TITLE
Switch to puppeteer-core

### PR DESCRIPTION
**Pull request by jkrems**
This prevents the download of Chrome on every install of testium.

---
_This PR was started by: [git wf pr](https://github.groupondev.com/InteractionTier/workflow-cli/releases/tag/v1.8.1)_

### CODE REVIEW

**Comment by jkrems** [comment]
Seeing the following:

```
  1) puppeteer exposes device emulation:
     Error: Protocol error (Target.getBrowserContexts): Not allowed.
```

**Comment by jkrems** [comment]
Same error happens on master so I don't think this is a regression.

**Comment by dbushong** [comment]
Confirmed on local master.  Possibilities:

1. it's a bad test
2. we're handing puppeteer our local browser that testium uses, so when we say `testium_browser=chrome` even though we were using the "full" version of puppeteer, it was still using the chrome we handed it, and thus there's no reason to NOT use puppeteer-core

I suspect the latter, but that also raises the concern that if this protocol is so brittle that it breaks with slight version slides, maybe we should rethink our puppeteer integration.

**Comment by jkrems** [comment]
(Closed because I'm cleaning up old PRs and I'm unlikely to work on this anytime soon. :))

**Pull request closed without merging**
