### PR TITLE
chore: upgrade packages

### PR DESCRIPTION
**Pull request by aaarichter**

### CODE REVIEW

**Comment by aotarola** [comment]
mm CI complains in `Node 8` about the usage of `Url`. Should we drop `Node 8` support and major bump?

**Comment by dbushong** [comment]
That's just nlm breaking because it requires 10.  If we don't need to major bump now, I'd just downgrade nlm back to 3.x

**Comment by aaarichter** [comment]
downgraded packages to support node8

**Comment by aaarichter** [comment]
if we do a major then I'd upgrade lighthouse (make https://github.com/testiumjs/testium-driver-wd/pull/42 obsolete) and `puppeteer`. the later will be hard because the existing test is not running. when changing the testiumrc to chrome browser, the test fails in the current master. So this will likely be tricky

**Pull request merged**
